# Day 24 — PyTorch Basics

Topics covered:
- Tensors
- Tensor operations
- Autograd
- Gradients
- nn.Module
- Simple neural network

In [4]:
import torch
import torch.nn as nn

print(torch.__version__)

2.13.0+cpu


In [5]:
# Scalar
a = torch.tensor(5)

# Vector
b = torch.tensor([1, 2, 3])

# Matrix
c = torch.tensor([
    [1, 2],
    [3, 4]
])

print("Scalar:")
print(a)

print("\nVector:")
print(b)

print("\nMatrix:")
print(c)

Scalar:
tensor(5)

Vector:
tensor([1, 2, 3])

Matrix:
tensor([[1, 2],
        [3, 4]])


In [6]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)

Shape of a: torch.Size([])
Shape of b: torch.Size([3])
Shape of c: torch.Size([2, 2])


In [7]:
zeros = torch.zeros(2, 3)
ones = torch.ones(2, 3)
random_tensor = torch.rand(2, 3)

print("Zeros:")
print(zeros)

print("\nOnes:")
print(ones)

print("\nRandom:")
print(random_tensor)

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random:
tensor([[0.1928, 0.1949, 0.5168],
        [0.5240, 0.9293, 0.9183]])


In [8]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)

Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([0.2500, 0.4000, 0.5000])


In [9]:
X = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

W = torch.tensor([
    [0.5, 0.2],
    [0.1, 0.7]
])

result = torch.matmul(X, W)

print(result)

ans= X@W

print(ans)

tensor([[0.7000, 1.6000],
        [1.9000, 3.4000]])
tensor([[0.7000, 1.6000],
        [1.9000, 3.4000]])


In [10]:
x = torch.tensor(3.0, requires_grad=True)

y = x ** 2

y.backward()

print("x:", x)
print("y:", y)
print("dy/dx:", x.grad)

x: tensor(3., requires_grad=True)
y: tensor(9., grad_fn=<PowBackward0>)
dy/dx: tensor(6.)


In [11]:
x = torch.tensor(2.0, requires_grad=True)

y = 3 * x**2 + 2 * x + 1

y.backward()

print("y =", y.item())
print("Gradient =", x.grad.item())

y = 17.0
Gradient = 14.0


In [12]:
import torch
import torch.nn as nn
class SimpleNN(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.layer1 = nn.Linear(2, 4)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(4, 1)
    
    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        
        return x

In [13]:
model = SimpleNN()
print(model)

SimpleNN(
  (layer1): Linear(in_features=2, out_features=4, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=4, out_features=1, bias=True)
)


In [14]:
input_data = torch.tensor([
    [1.0, 2.0]
])

output = model(input_data)

print("Input:")
print(input_data)

print("\nOutput:")
print(output)

Input:
tensor([[1., 2.]])

Output:
tensor([[1.2892]], grad_fn=<AddmmBackward0>)


In [24]:
input_data = torch.tensor([
    [1.0, 2.0]
])

output = model(input_data)

print("Input:")
print(input_data)

print("\nOutput:")
print(output)

Input:
tensor([[1., 2.]])

Output:
tensor([[1.2892]], grad_fn=<AddmmBackward0>)


In [25]:
for name, param in model.named_parameters():
    print(name)
    print(param)
    print()

layer1.weight
Parameter containing:
tensor([[-0.0703,  0.4370],
        [ 0.1541, -0.1017],
        [ 0.2262, -0.3048],
        [ 0.2263,  0.4711]], requires_grad=True)

layer1.bias
Parameter containing:
tensor([ 0.3599,  0.3659, -0.4610,  0.1710], requires_grad=True)

layer2.weight
Parameter containing:
tensor([[0.2489, 0.4117, 0.3812, 0.4080]], requires_grad=True)

layer2.bias
Parameter containing:
tensor([0.3229], requires_grad=True)



In [26]:
model = SimpleNN()

X = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

y_true = torch.tensor([
    [1.0],
    [0.0]
])

prediction = model(X)

loss = torch.mean((prediction - y_true) ** 2)

print("Prediction:")
print(prediction)

print("\nLoss:")
print(loss.item())

Prediction:
tensor([[1.0449],
        [2.3839]], grad_fn=<AddmmBackward0>)

Loss:
2.8425586223602295
