In [1]:
import torch
import torch.nn.functional as F

In [2]:
Q = torch.tensor([[1.0, 0.0]])

K = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0]
])

V = torch.tensor([
    [10.0, 0.0],
    [0.0, 10.0],
    [5.0, 5.0]
])

In [3]:
scores = Q @ K.T

print(scores)

tensor([[1., 0., 1.]])


In [4]:
attention_weights = F.softmax(scores, dim=-1)

print(attention_weights)

tensor([[0.4223, 0.1554, 0.4223]])


In [5]:
output = attention_weights @ V

print(output)

tensor([[6.3348, 3.6652]])


In [6]:
d_k = K.shape[-1]

scores = (Q @ K.T) / torch.sqrt(
    torch.tensor(d_k, dtype=torch.float32)
)

In [8]:
attention_weights = F.softmax(scores, dim=-1)

output = attention_weights @ V

print(output)

tensor([[6.0167, 3.9833]])
